### ISSUE TITLE
maybe find a redundant line of code

### ISSUE THREAD

**Issue by SnowJF** [dylan8902/xss-auditor#1]
Thank you for sharing the xss-auditor theory code. Since I am learning xss recently, the code helped me a lot to understand the work browser does.

   When I read and tested your code line by line, I found a line of code "updateUI(this);" in the class Test's constructor function.  I think this line is redundant as there is no test result to update in the constructing stage.
   
    Because I am new for both github and xss, if there is something wrong in what i mentioned, welcome your suggestion, thank you!

**Comment by dylan8902** [comment]
Hello, Thanks for your comment!

That call to update the UI in the constructor is adding the test case to the UI as soon as it is created so the user can see the tests that will be run. The results are then updated when the requests have completed. 
It is mainly so there isn't an empty box while all the AJAX requests are made.

Thanks again.
